version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - printenv
      - echo Build completed on `date`
artifacts:
  files:
    - target/onnee-0.0.1-SNAPSHOT.jar