version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build ended on `date`
      - mv build/libs/*.jar app.jar
artifacts:
  files:
    - app.jar