spring:
  # Security configuration
  # Database
  datasource:
    url: jdbc:postgresql://onnee-app.c1ekes4du2kc.us-east-1.rds.amazonaws.com:5432/onnee
    username: postgres
    password: 1144admin
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always # Spring Boot >=v2.5.0
