spring:
  # Security configuration
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PW}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always # Spring Boot >=v2.5.0
